-- Generated by hyprvalidate convert --split.
--
-- Deployment note: require() resolves modules relative to the directory
-- this file lives in, so copy every .lua file here flat into
-- ~/.config/hypr/ (this file must stay named hyprland.lua there). Nesting
-- the modules one level deeper needs extra package.path setup.
--
-- Order below follows the original config's own order. Each require() runs
-- its module body immediately, so statements that depend on order (repeated
-- config keys, duplicate binds, window-rule precedence) keep the relative
-- order they had in the source file.

require("other")
require("monitors")
require("autostart")
require("env")
require("input")
require("appearance")
require("windowrules")
require("layerrules")
require("keybinds")
